import {
  Activity,
  AlertTriangle,
  ArrowRight,
  BarChart3,
  Bot,
  Box,
  Check,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  DollarSign,
  File,
  FileText,
  Gauge,
  HelpCircle,
  Home,
  Image,
  KanbanSquare,
  Laptop,
  LayoutDashboard,
  Loader2,
  LogIn,
  Moon,
  MoreVertical,
  Plus,
  Settings,
  Sparkles,
  Sun,
  Trash,
  User,
  UserCircle,
  X,
  Zap,
  Wrench,
  Layers,
  type LucideIcon
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  dashboard: LayoutDashboard,
  logo: Command,
  login: LogIn,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  page: File,
  post: FileText,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  user2: UserCircle,
  arrowRight: ArrowRight,
  help: HelpCircle,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  check: Check,
  // FlowForge specific icons
  activity: Activity,
  barChart: BarChart3,
  box: Box,
  gauge: Gauge,
  wrench: Wrench,
  zap: Zap,
  checkCircle: CheckCircle,
  layers: Layers,
  home: Home,
  // New: Team & PM icons
  bot: Bot,
  kanban: KanbanSquare,
  sparkles: Sparkles,
  dollarSign: DollarSign,
};
